### ISSUE TITLE
Dark Mode changes colors in Dye preview

### ISSUE THREAD

**Issue by Almdoodler** [gw2efficiency/issues#1434]
As can be seen in the attached images the preview of Dyes is inconsistent between the Light and Dark Mode of the website. This seems to affect all color previews, but seems to be most noticeable for lighter colors such as Vision and Guiding Star, which are plain white in Dark Mode but light yellow/orangish in Light Mode.

![GW2Efficency Bug report](https://user-images.githubusercontent.com/8082125/120124476-e084b680-c1b4-11eb-9ec6-639e73c6c1c2.png)

This behavior seems to be caused by the following CSS rule inside [nightmode.css](https://gw2efficiency.com/assets/nightmode.css) (specifically line 28) and can be reproduced within Google Chrome (91.0.4472.77) and Firefox(88.01):

```css
:not(object):not(body) > embed,
[style*="background:url"]:empty,
[style*="background-image:url"]:empty,
[style*="background: url"]:empty,
[style*="background-image: url"]:empty,
iframe,
img,
object,
svg image,
video,
i,
.copy-wrapper,
.noNightmode,
.eff-Button {
  filter: invert(100%) hue-rotate(180deg) !important;
  text-shadow: none !important;
}
```

While I know that `filter: invert(100%) hue-rotate(180deg) !important;` is the de facto standard way of implementing dark modes, it seems to break in this specific case.
