### ISSUE TITLE
Add "night mode"

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#51]
Multiple people asked for the ability to flip the page into a night mode, where most of the whites are replaced by gray/blacks. 
- Flip the background to black
- Use the new background color as outline for better underlines
- Clean up icons
- Fix most of the cases where transparency is used

**Comment by queicherius** [comment]
```css
html {
  -webkit-filter: invert(100%) hue-rotate(180deg) brightness(150%) contrast(90%) !important;
}

img, iframe, video, *:not(object):not(body)>embed, object,
svg image,
*[style*="background:url"]:empty, *[style*="background-image:url"]:empty,
*[style*="background: url"]:empty, *[style*="background-image: url"]:empty {
  -webkit-filter: invert(100%) hue-rotate(180deg) !important;
}

html {
  text-shadow: 0 0 0 !important;
}

*:-webkit-full-screen, *:-webkit-full-screen * {
  -webkit-filter: none !important;
}

html {
  background: rgb(13,13,13) !important;
}
```
